import { foods, recipes } from "../data/nutrition";

export async function GET() {
  const SITE = "https://dinh-duong-viet.pages.dev";
  const staticPages = [
    "", "/thuc-pham", "/mon-an", "/tim-kiem", "/thong-ke", "/phuong-phap",
    "/kien-thuc-dinh-duong",
    "/kien-thuc-dinh-duong/thap-dinh-duong-viet-nam",
    "/kien-thuc-dinh-duong/thap-dinh-duong-my-nhat",
    "/kien-thuc-dinh-duong/nhu-cau-dinh-duong-khuyen-nghi",
    "/kien-thuc-dinh-duong/10-loi-khuyen-dinh-duong",
    "/kien-thuc-dinh-duong/beo-phi",
    "/kien-thuc-dinh-duong/dai-thao-duong",
    "/kien-thuc-dinh-duong/dau-da-day",
    "/kien-thuc-dinh-duong/gan-nhiem-mo",
    "/kien-thuc-dinh-duong/gout",
    "/kien-thuc-dinh-duong/loang-xuong",
    "/kien-thuc-dinh-duong/suy-than",
    "/kien-thuc-dinh-duong/tang-huyet-ap",
    "/kien-thuc-dinh-duong/thieu-mau",
    "/kien-thuc-dinh-duong/phu-nu-mang-thai",
    "/kien-thuc-dinh-duong/dinh-duong-tre-em",
    "/kien-thuc-dinh-duong/dinh-duong-nguoi-cao-tuoi",
    "/kien-thuc-dinh-duong/roi-loan-mo-mau",
    "/kien-thuc-dinh-duong/benh-tim-mach",
    "/kien-thuc-dinh-duong/tao-bon-ibs",
    "/kien-thuc-dinh-duong/dinh-duong-chay",
    "/kien-thuc-dinh-duong/ung-thu",
    "/kien-thuc-dinh-duong/vitamin-khoang-chat",
    "/kien-thuc-dinh-duong/an-toan-thuc-pham",
    "/kien-thuc-dinh-duong/chat-xo",
    "/kien-thuc-dinh-duong/hieu-dung-ve-calo",
    "/kien-thuc-dinh-duong/doc-nhan-dinh-duong",
    "/kien-thuc-dinh-duong/giam-can-khoa-hoc",
    "/kien-thuc-dinh-duong/tang-co-gym",
    "/kien-thuc-dinh-duong/trao-nguoc-da-day",
    "/kien-thuc-dinh-duong/uong-nuoc-dung-cach",
    "/kien-thuc-dinh-duong/canxi-xuong-chac-khoe",
    "/kien-thuc-dinh-duong/an-chay-truong",
    "/kien-thuc-dinh-duong/dau-da-day-nen-an-gi",
    "/kien-thuc-dinh-duong/dinh-duong-sau-phau-thuat",
    "/kien-thuc-dinh-duong/viem-dai-trang-tieu-hoa",
    "/kien-thuc-dinh-duong/trao-nguoc-ban-dem",
    "/kien-thuc-dinh-duong/thieu-vitamin-d",
    "/kien-thuc-dinh-duong/gan-nhiem-mo-nguoi-gay",
    "/kien-thuc-dinh-duong/thuoc-chi-dinh-vitamin-k",
    "/kien-thuc-dinh-duong/om-sot-cam-cum",
    "/kien-thuc-dinh-duong/tieu-chay-mat-nuoc",
    "/kien-thuc-dinh-duong/dinh-duong-cho-nguoi-kho-nuot",
    "/kien-thuc-dinh-duong/muoi-duong-trong-thuc-pham",
    "/kien-thuc-dinh-duong/suy-dinh-duong-nguoi-benh",
    "/kien-thuc-dinh-duong/men-gan-cao",
    "/kien-thuc-dinh-duong/tang-acid-uric",
    "/kien-thuc-dinh-duong/trung-thuc-pham",
    "/kien-thuc-dinh-duong/com-trang-tieu-duong",
    "/kien-thuc-dinh-duong/dot-quy-dinh-duong",
    "/kien-thuc-dinh-duong/dinh-duong-suy-tim",
    "/kien-thuc-dinh-duong/di-cho-tieu-duong",
    "/kien-thuc-dinh-duong/tu-lanh-lanh-manh",
    "/kien-thuc-dinh-duong/chon-sua-nguoi-gia",
    "/kien-thuc-dinh-duong/chon-dau-an",
    "/kien-thuc-dinh-duong/an-quan-khi-benh-nen",
    "/kien-thuc-dinh-duong/goi-mon-tiec-cuoi",
    "/kien-thuc-dinh-duong/giam-muoi-mon-ngon",
    "/kien-thuc-dinh-duong/tang-rau-com-viet",
    "/kien-thuc-dinh-duong/them-dam-nguoi-gia",
    "/kien-thuc-dinh-duong/doc-nhan-thuc-pham",
    "/kien-thuc-dinh-duong/banh-mi-goc-nhin-dinh-duong",
    "/kien-thuc-dinh-duong/chao-goc-nhin-dinh-duong",
    "/kien-thuc-dinh-duong/com-tam-goc-nhin-dinh-duong",
    "/kien-thuc-dinh-duong/mon-kho-goc-nhin-dinh-duong",
    "/kien-thuc-dinh-duong/canh-goc-nhin-dinh-duong",
    "/kien-thuc-dinh-duong/do-chien-goc-nhin-dinh-duong",
    "/kien-thuc-dinh-duong/nuoc-cham-goc-nhin-dinh-duong",
    "/kien-thuc-dinh-duong/tra-sua-goc-nhin-dinh-duong",
    "/cong-cu/nuoc-muoi-mon-an",
    "/cong-cu/khau-phan-don-gian",
    "/cong-cu/checklist-an-uong",
    "/cong-cu/dia-an-lanh-manh",
    "/kien-thuc-dinh-duong/thuc-don-tieu-duong",
    "/kien-thuc-dinh-duong/thuc-don-tieu-duong-binh-dan",
    "/kien-thuc-dinh-duong/thuc-don-tieu-duong-ban-ron",
    "/kien-thuc-dinh-duong/thuc-don-tieu-duong-nguoi-gia",
    "/kien-thuc-dinh-duong/thuc-don-huyet-ap-binh-dan",
    "/kien-thuc-dinh-duong/thuc-don-huyet-ap-ban-ron",
    "/kien-thuc-dinh-duong/thuc-don-huyet-ap-nguoi-gia",
    "/kien-thuc-dinh-duong/thuc-don-gout-binh-dan",
    "/kien-thuc-dinh-duong/thuc-don-gout-ban-ron",
    "/kien-thuc-dinh-duong/thuc-don-gout-nguoi-gia",
    "/kien-thuc-dinh-duong/thuc-don-gan-nhiem-mo-binh-dan",
    "/kien-thuc-dinh-duong/thuc-don-gan-nhiem-mo-ban-ron",
    "/kien-thuc-dinh-duong/thuc-don-gan-nhiem-mo-nguoi-gia",
    "/kien-thuc-dinh-duong/thuc-don-da-day-binh-dan",
    "/kien-thuc-dinh-duong/thuc-don-da-day-ban-ron",
    "/kien-thuc-dinh-duong/thuc-don-da-day-nguoi-gia",
    "/kien-thuc-dinh-duong/thuc-don-tang-huyet-ap",
    "/kien-thuc-dinh-duong/thuc-don-gout",
    "/kien-thuc-dinh-duong/thuc-don-gan-nhiem-mo",
    "/kien-thuc-dinh-duong/thuc-don-mo-mau",
    "/kien-thuc-dinh-duong/thuc-don-da-day",
    "/kien-thuc-dinh-duong/thuc-don-tang-dam-nguoi-gay",
    "/kien-thuc-dinh-duong/thuc-don-giam-can-kieu-viet",
    "/kien-thuc-dinh-duong/bua-sang-lanh-manh-kieu-viet",
    "/kien-thuc-dinh-duong/bua-toi-nhe-de-ngu",
    "/kien-thuc-dinh-duong/sai-lam-tieu-duong-bo-com",
    "/kien-thuc-dinh-duong/sai-lam-gout-chi-do-thit",
    "/kien-thuc-dinh-duong/sai-lam-gan-nhiem-mo-an-mo",
    "/kien-thuc-dinh-duong/sai-lam-loang-xuong-chi-canxi",
    "/kien-thuc-dinh-duong/sai-lam-thieu-mau-uong-sat",
    "/kien-thuc-dinh-duong/sai-lam-sua-dinh-duong-thay-bua-an",
    "/kien-thuc-dinh-duong/sai-lam-trai-cay-nhieu-tot",
    "/kien-thuc-dinh-duong/nuoc-ep-khong-nhu-trai-cay",
    "/kien-thuc-dinh-duong/an-ca-kip-truc",
    "/kien-thuc-dinh-duong/an-du-lich-benh-nen",
    "/kien-thuc-dinh-duong/an-ngoai-hang-quan",
    "/kien-thuc-dinh-duong/mam-com-gia-dinh-benh-nen",
    "/kien-thuc-dinh-duong/an-tet-nguoi-benh",
    "/kien-thuc-dinh-duong/an-khuya-va-nhin-an-gian-doan",
    "/kien-thuc-dinh-duong/sua-ai-nen-uong",
    "/kien-thuc-dinh-duong/bun-pho-mi-duong-huyet",
    "/kien-thuc-dinh-duong/ca-phe-uong-sao-cho-loi",
    "/kien-thuc-dinh-duong/dau-an-mo-heo",
    "/kien-thuc-dinh-duong/nuoc-ham-xuong-canxi",
    "/kien-thuc-dinh-duong/noi-tang-dong-vat",
    "/kien-thuc-dinh-duong/rau-cu-dong-lanh-do-hop",
    "/kien-thuc-dinh-duong/day-bung-sau-an",
    "/kien-thuc-dinh-duong/o-nong-nong-rat-nguc",
    "/kien-thuc-dinh-duong/tieu-chay-o-nguoi-lon",
    "/kien-thuc-dinh-duong/chan-an-nguoi-cao-tuoi",
    "/kien-thuc-dinh-duong/chuot-rut-thieu-chat",
    "/kien-thuc-dinh-duong/phu-chan-giam-muoi",
    "/kien-thuc-dinh-duong/rung-toc-thieu-chat",
    "/kien-thuc-dinh-duong/dinh-duong-viem-gan",
    "/kien-thuc-dinh-duong/dinh-duong-basedow-cuong-giap",
    "/kien-thuc-dinh-duong/tien-dai-thao-duong",
    "/hoi-dap",
    "/theo-benh",
    "/theo-benh/tieu-duong",
    "/theo-benh/cao-huyet-ap",
    "/theo-benh/gout-axit-uric",
    "/theo-benh/gan-nhiem-mo",
    "/theo-benh/da-day-trao-nguoc",
    "/theo-benh/benh-than",
    "/theo-benh/mo-mau-tim-mach",
    "/ban-do-benh",
    "/kien-thuc-dinh-duong/che-do-dash-tang-huyet-ap",
    "/kien-thuc-dinh-duong/sai-lam-giam-can",
    "/kien-thuc-dinh-duong/sai-lam-an-nhat",
    "/kien-thuc-dinh-duong/tao-bon-nguoi-cao-tuoi",
    "/kien-thuc-dinh-duong/met-moi-thieu-chat",
    "/kien-thuc-dinh-duong/thuc-pham-giac-ngu",
    "/kien-thuc-dinh-duong/che-do-trung-hai-viem-khop-tim-mach",
    "/kien-thuc-dinh-duong/dinh-duong-viem-khop",
    "/kien-thuc-dinh-duong/soi-than-dinh-duong",
    "/kien-thuc-dinh-duong/hoi-chung-chuyen-hoa",
    "/kien-thuc-dinh-duong/probiotic-va-duong-ruot",
    "/kien-thuc-dinh-duong/chon-dau-an-lanh-manh",
    "/kien-thuc-dinh-duong/dinh-duong-dan-van-phong",
    "/kien-thuc-dinh-duong/dinh-duong-thuc-khuya",
    "/kien-thuc-dinh-duong/bua-sang-lanh-manh",
    "/kien-thuc-dinh-duong/an-ngoai-goi-do-an",
    "/cong-cu",
    "/cong-cu/bmi",
    "/cong-cu/nuoc-uong",
    "/cong-cu/loc-thuc-pham",
    "/cong-cu/doi-don-vi",
    "/cong-cu/so-sanh-thuc-pham",
    "/cong-cu/so-sanh-bua-an",
    "/cong-cu/bang-xep-hang",
    "/cong-cu/duong-do-uong",
    "/cong-cu/danh-sach-di-cho",
    "/cong-cu/tim-mon-tu-nguyen-lieu",
    "/cong-cu/them-thuc-pham-dong-goi",
    "/cong-cu/nhat-ky",
    "/cong-cu/lap-thuc-don-tuan",
    "/cong-cu/ke-hoach-bua-an",
    "/cong-cu/theo-doi-suc-khoe",
    "/cong-cu/tuong-tac-thuoc",
    "/cong-cu/khau-phan-viet-clinical",
    "/cong-cu/muc-tieu-can-nang",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-com-tieu-duong",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-gout-dam",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-suy-than-kieng",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-gan-bo-gan",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-nuoc-ep-trai-cay",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-an-nhat-muoi",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-sua-hat-dam",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-nuoc-ham-xuong",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-thuc-pham-chuc-nang",
    "/kien-thuc-dinh-duong/canh-bao-hieu-lam-giam-can-nhanh",
  ];

  let urls = staticPages.map(p => ({
    loc: SITE + p,
    changefreq: "weekly",
    priority: p === "" ? "1.0" : p.startsWith("/thuc-pham/") || p.startsWith("/mon-an/") ? "0.8" : "0.6",
  }));

  foods.forEach(f => {
    urls.push({
      loc: SITE + "/thuc-pham/" + f.slug,
      changefreq: "monthly",
      priority: "0.5",
    });
  });

  recipes.forEach(r => {
    urls.push({
      loc: SITE + "/mon-an/" + r.slug,
      changefreq: "monthly",
      priority: "0.5",
    });
  });

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>\n    <loc>${u.loc}</loc>\n    <changefreq>${u.changefreq}</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`).join("\n")}
</urlset>`;

  return new Response(xml, {
    headers: { "Content-Type": "application/xml" },
  });
}
